on:
  push:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm version --no-git-tag-version patch
      - run: npm install
      - run: npm ci
      - run: npm run compile
      - run: mv ./dist/Kindle-Companion*.exe ./dist/Kindle-Companion.exe
      - name: Upload artifact .exe
        uses: actions/upload-artifact@v3
        with:
          name: Kindle-Companion.exe
          path: ./dist/Kindle-Companion.exe

  build_macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm version --no-git-tag-version patch
      - run: npm install
      - run: npm ci
      - run: npm run compile
      - run: mv ./dist/Kindle-Companion*.dmg ./dist/Kindle-Companion.dmg
      - name: Upload artifact .dmg
        uses: actions/upload-artifact@v3
        with:
          name: Kindle-Companion.dmg
          path: ./dist/Kindle-Companion.dmg

  build_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: install missing dependencies
        run: sudo apt-get install -y libarchive-tools
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm version --no-git-tag-version patch
      - run: npm install
      - run: npm ci
      - run: npm run compile
      - run: |
          mv ./dist/Kindle-Companion*.deb ./dist/Kindle-Companion.deb
          mv ./dist/Kindle-Companion*.snap ./dist/Kindle-Companion.snap
      - name: Upload artifact .deb
        uses: actions/upload-artifact@v3
        with:
          name: Kindle-Companion.deb
          path: ./dist/Kindle-Companion.deb
      - name: Upload artifact .snap
        uses: actions/upload-artifact@v3
        with:
          name: Kindle-Companion.snap
          path: ./dist/Kindle-Companion.snap